import React from 'react';

function Lorems(intensidad) {

    if (intensidad == 1) {
        return (
            <p>
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Asperiores harum fugit, autem vel nesciunt assumenda unde reiciendis. Libero excepturi quia, aut quod qui doloribus fugiat ipsa minima, sapiente unde recusandae? Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, eveniet. Autem ex, fugiat nihil omnis provident accusamus dolorum nobis tenetur magnam ipsa reiciendis illum ullam quidem blanditiis animi commodi voluptas! Lorem ipsum,
            </p>
        )
    }
    if (intensidad == 2) {
        return (
            <p>
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Asperiores harum fugit, autem vel nesciunt assumenda unde reiciendis. Libero excepturi quia, aut quod qui doloribus fugiat ipsa minima, sapiente unde recusandae? Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, eveniet. Autem ex, fugiat nihil omnis provident accusamus dolorum nobis tenetur magnam ipsa reiciendis illum ullam quidem blanditiis animi commodi voluptas! Lorem ipsum,tenetur magnam ipsa reiciendis illum ullam quidem blanditiis animi commodi voluptas! Lorem ipsum,t. Aspernatur eaque illum perferendis repellendus corporis eveniet! Libero labore odio, ab incidunt voluptates debitis qui fuga unde sit aut, facere earum eligendi. Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta placeat facere repellat dolore numquam sit eveniet sapiente amet quisquam inventore, non delectus cumque voluptas porro explicabo officia ratione ea quod. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Magnam nisi amet tempora iusto blanditiis ex beatae eveniet fuga, quod, eos non consectetur nihil repellat quis eius? Animi assumenda laboriosam amet?<br />
            </p>
        )
    }
    if (intensidad == 3) {
        return (
            <p>
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Asperiores harum fugit, autem vel nesciunt assumenda unde reiciendis. Libero excepturi quia, aut quod qui doloribus fugiat ipsa minima, sapiente unde recusandae? Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, eveniet. Autem ex, fugiat nihil omnis provident accusamus dolorum nobis tenetur magnam ipsa reiciendis illum ullam quidem blanditiis animi commodi voluptas! Lorem ipsum,t. Aspernatur eaque illum perferendis repellendus corporis eveniet! Libero labore odio, ab incidunt voluptates debitis qui fuga unde sit aut, facere earum eligendi. Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta placeat facere repellat dolore numquam sit eveniet sapiente amet quisquam inventore, non delectus cumque voluptas porro explicabo officia ratione ea quod. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Magnam nisi amet tempora iusto blanditiis ex beatae eveniet fuga, quod, eos non consectetur nihil repellat quis eius? Animi assumenda laboriosam amet?<br />
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Asperiores harum fugit, autem vel nesciunt assumenda unde reiciendis. Libero excepturi quia, aut quod qui doloribus fugiat ipsa minima, sapiente unde recusandae? Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, eveniet. Autem ex, fugiat nihil omnis provident accusamus dolorum nobis tenetur magnam ipsa reiciendis illum ullam quidem blanditiis animi commodi voluptas! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eos dolorum laudantium debitis sint aliquid excepturi, deserunt distinctio sapiente quod corporis dolor omnis molestiae sed placeat rem repellendus ea unde? Ullam. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sit, veritatis quae excepturi voluptatum sed commodi dolorum eos culpa id laudantium vitae quo odio, dolores aperiam, voluptatibus incidunt ea maiores vero. Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis delectus explicabo asperiores iu<br />sto minus, at perferendis itaque eos, ducimus molestiae rerum suscipit aliquid, voluptas neque sed repudiandae reiciendis magnam laboriosam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur eaque illum perferendis repellendus corporis eveniet! Libero labore odio, ab incidunt voluptates debitis qui fuga unde sit aut, facere earum eligendi. Lorem ipsum dolor sit amet constenetur magnam ipsa reiciendis illum ullam quidem blanditiis animi commodi voluptas! Lorem ipsum,t. Aspernatur eaque illum perferendis repellendus corporis eveniet! Libero labore odio, ab incidunt voluptates debitis qui fuga unde sit aut, facere earum eligendi. Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta placeat facere repellat dolore numquam sit eveniet sapiente amet quisquam inventore, non delectus cumque voluptas porro explicabo officia ratione ea quod. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Magnam nisi amet tempora iusto blanditiis ex beatae eveniet fuga, quod, eos non consectetur nihil repellat quis eius? Animi assumenda laboriosam amet?<br />
            </p>
        )
    }

    if (intensidad == 4) {
        return (
            <p>
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Asperiores harum fugit, autem vel nesciunt assumenda unde reiciendis. Libero excepturi quia, aut quod qui doloribus fugiat ipsa minima, sapiente unde recusandae? Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, eveniet. Autem ex, fugiat nihil omnis provident accusamus dolorum nobis tenetur magnam ipsa reiciendis illum ullam quidem blanditiis animi commodi voluptas! Lorem ipsum,<br /> dolor sit amet consectetur adipisicing elit. Eos dolorum laudantium debitis sint aliquid excepturi, deserunt distinctio sapiente quod corporis dolor omnis molestiae sed placeat rem repellendus ea unde? Ullam. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sit, veritatis quae excepturi voluptatum sed commodi dolorum eos culpa id laudantium vitae quo odio, dolores aperiam, voluptatibus incidunt ea maiores vero. Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis delectus explicabo asperiores iusto minus, at perferendis itaque eos, ducimus molestiae rerum suscipit aliquid, voluptas neque sed repudiandae reiciendis magnam laboriosam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur eaque illum perferendis repellendus corporis eveniet! Libero labore odio, ab incidunt voluptates debitis qui fuga unde sit aut, facere earum eligendi. Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta placeat facere repellat dolore numquam sit eveniet sapiente amet quisquam inventore, non delectus cumque voluptas porro explicabo officia ratione ea quod. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Magnam nisi amet tempora iusto blanditiis ex beatae eveniet fuga, quod, eos non consectetur nihil repellat quis eius? Animi assumenda laboriosam amet?<br />
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Asperiores harum fugit, autem vel nesciunt assumenda unde reiciendis. Libero excepturi quia, aut quod qui doloribus fugiat ipsa minima, sapiente unde recusandae? Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, eveniet. Autem ex, fugiat nihil omnis provident accusamus dolorum nobis tenetur magnam ipsa reiciendis illum ullam quidem blanditiis animi commodi voluptas! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eos dolorum laudantium debitis sint aliquid excepturi, deserunt distinctio sapiente quod corporis dolor omnis molestiae sed placeat rem repellendus ea unde? Ullam. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sit, veritatis quae excepturi voluptatum sed commodi dolorum eos culpa id laudantium vitae quo odio, dolores aperiam, voluptatibus incidunt ea maiores vero. Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis delectus explicabo asperiores iu<br />sto minus, at perferendis itaque eos, ducimus molestiae rerum suscipit aliquid, voluptas neque sed repudiandae reiciendis magnam laboriosam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur eaque illum perferendis repellendus corporis eveniet! Libero labore odio, ab incidunt voluptates debitis qui fuga unde sit aut, facere earum eligendi. Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta placeat facere repellat dolore numquam sit eveniet sapiente amet quisquam inventore, non delectus cumque voluptas porro explicabo officia ratione ea quod. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Magnam nisi amet tempora iusto blanditiis ex beatae eveniet fuga, quod, eos non consectetur nihil repellat quis eius? Animi assumenda laboriosam amet?<br />
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Asperiores harum fugit, autem vel nesciunt assumenda unde reiciendis. Libero excepturi quia, aut quod qui doloribus fugiat ipsa minima, sapiente unde recusandae? Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, eveniet. Autem ex, fugiat nihil omnis provident accusamus dolorum nobis tenetur magnam ipsa reiciendis illum ullam quidem blanditiis animi commodi voluptas! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eos dolorum laudantium debitis sint aliquid excepturi, deserunt distinctio sapiente quod corporis dolor omnis molestiae sed placeat rem repellendus ea unde? Ullam. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sit, veritatis quae excepturi voluptatum sed commodi dolorum eos culpa id laudantium vitae quo odio, dolores aperiam, voluptatibus incidunt ea maiores vero. Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis delectus explicabo asperiores iusto minus, at perferendis itaque eos, ducimus molestiae rerum suscipit aliquid, voluptas neque sed repudiandae reiciendis magnam l<br />aboriosam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur eaque illum perferendis repellendus corporis eveniet! Libero labore odio, ab incidunt voluptates debitis qui fuga unde sit aut, facere earum eligendi. Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta placeat facere repellat dolore numquam sit eveniet sapiente amet quisquam inventore, non delectus cumque voluptas porro explicabo officia ratione ea quod. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Magnam nisi amet tempora iusto blanditiis ex beatae eveniet fuga, quod, eos non consectetur nihil repellat quis eius? Animi assumenda laboriosam amet?<br />
            </p>
        )
    }
}

function Fotos() {

    return (
        <>

        </>
    )
}

export { Lorems, Fotos }